### ISSUE TITLE
Not Approved anymore?

### ISSUE THREAD

**Issue by Helix25** [trumank/drg-custom-difficulties#8]
Hi, 

First of all thanks for an awsome mod, me and my friends have hade alot of fun times with this one!
Now to my question: Is the mod not approved anymore?
Since about 3 weeks ago it appears you cant use this in a normal game, instead you need to start a sandbox type game.

Is there a plan to fix this or what's the status?

**Comment by trumank** [comment]
The mod has the `Approved` tag on mod.io so any issues causing your lobby to be forced into sandbox are from DRG's flaky modding system and aren't specific to the mod itself. Sadly all I can suggest is going through common troubleshooting steps such as reinstalling mods via unsubscribing/resubscribing.
