### ISSUE TITLE
Not sure how to apply pawn stat changes to the player

### ISSUE THREAD

**Issue by Halex000** [trumank/drg-custom-difficulties#9]
I want to change the pawn stats of the player, looking at your schematic json, on line 161 it shows that you should be able to just have "pawnStats": {} as a difficulty attribute but when I try this the game says the warning "Unknown difficulty attribute: PawnStats". Is this a bug with trying to apply pawn stat changes to the player or am I doing it wrong?

**Comment by trumank** [comment]
Ah no, `PawnStats` can only be applied to `EnemyDescriptors`. They are referenced only by the `enemyDescriptor` object on line 158: https://github.com/trumank/drg-custom-difficulties/blob/942db0784ad1d705162ad08b9774de1d9d255602/cd.schema.json#L158 Custom Difficulty does not provide a way to apply them to players (even though most of them only affect players).
